// Verify consistent handling of negative seq_ids across all llama_memory implementations.
//
// Semantics under test [TAG_LLAMA_SEQ_ID_NEG]:
//   - seq_id < 0 : "match any sequence" wildcard in llama_memory_seq_rm() and in the
//     whole-context state APIs - ANY negative value must behave exactly like -1
//   - llama_memory_seq_cp()/seq_keep()/seq_add()/seq_div()/seq_pos_min()/seq_pos_max()
//     require a concrete sequence: any negative (or out-of-range) seq_id must be
//     rejected without touching the memory and without crashing
//   - the valid seq-id range follows the KV mapping: [0, n_seq_max), or [0, LLAMA_MAX_SEQ)
//     with --kv-unified. A seq_id above n_seq_max is then valid and every cache of the
//     memory must act on it together: seq_keep(big) drops the rest in all of them.
//     A memory cleared in one cache only is the regression this catches
//   - after every removal the memory must stay decodable (stale tails crash the next decode)
//
// Runs over the dummy models generated by test-llama-archs, so every llama_memory
// implementation (kv-cache, recurrent, hybrid, ...) is covered.

#include "arg.h"
#include "common.h"
#include "log.h"
#include "llama-cpp.h"
#include "llama.h"

#include "../src/llama-cparams.h" // LLAMA_MAX_SEQ

#include <clocale>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>

enum class test_status {
    PASS,
    FAIL,
    SKIP,
};

static const char * test_status_str(test_status status) {
    switch (status) {
        case test_status::PASS: return "\033[1;32mPASS\033[m";
        case test_status::FAIL: return "\033[1;31mFAIL\033[m";
        case test_status::SKIP: return "\033[1;33mSKIP\033[m";
    }
    return "";
}

constexpr uint32_t  N_SEQ_MAX = 2;
constexpr int       N_FILL    = 4;

// seq ids used by the checks:
//   NEG     : always invalid - negative ids are only wildcards
//   TOO_BIG : always invalid - above the hardest cap, LLAMA_MAX_SEQ
//   BIG     : above n_seq_max but inside the unified range - valid with --kv-unified, refused without
constexpr llama_seq_id NEG     = -2;
constexpr llama_seq_id TOO_BIG = LLAMA_MAX_SEQ + 5;
constexpr llama_seq_id BIG     = N_SEQ_MAX + 5;

static bool decode_one(llama_context * ctx, llama_token tok, llama_pos pos, llama_seq_id seq) {
    common_batch batch(ctx);
    batch.add(tok, pos, seq, true);
    return llama_process(ctx, LLAMA_PROCESS_TYPE_DECODE, batch.get()) == 0;
}

// one token per position per sequence, so both sequences hold positions [0, N_FILL)
static bool fill_seqs(llama_context * ctx) {
    for (llama_pos p = 0; p < N_FILL; ++p) {
        for (llama_seq_id s = 0; s < (llama_seq_id) N_SEQ_MAX; ++s) {
            if (!decode_one(ctx, 0, p, s)) {
                return false;
            }
        }
    }
    llama_synchronize(ctx);
    return true;
}

// decode one more token per sequence right after its last stored position: the memory
// must stay usable after any removal (stale tails crash the next decode)
static bool decode_after(llama_context * ctx) {
    const llama_memory_t mem = llama_get_memory(ctx);

    llama_pos last[N_SEQ_MAX];

    for (llama_seq_id s = 0; s < (llama_seq_id) N_SEQ_MAX; ++s) {
        last[s] = llama_memory_seq_pos_max(mem, s);
        if (!decode_one(ctx, 0, last[s] + 1, s)) {
            return false;
        }
    }
    llama_synchronize(ctx);

    for (llama_seq_id s = 0; s < (llama_seq_id) N_SEQ_MAX; ++s) {
        if (llama_memory_seq_pos_max(mem, s) != last[s] + 1) {
            return false;
        }
    }

    return true;
}

struct mem_snapshot {
    llama_pos pos[N_SEQ_MAX][2]; // [seq][min, max]

    bool operator==(const mem_snapshot & other) const {
        return memcmp(pos, other.pos, sizeof(pos)) == 0;
    }
};

static mem_snapshot snapshot(llama_context * ctx) {
    mem_snapshot res;
    llama_memory_t mem = llama_get_memory(ctx);
    for (llama_seq_id s = 0; s < (llama_seq_id) N_SEQ_MAX; ++s) {
        res.pos[s][0] = llama_memory_seq_pos_min(mem, s);
        res.pos[s][1] = llama_memory_seq_pos_max(mem, s);
    }
    return res;
}

static bool snap_is_empty(const mem_snapshot & s) {
    for (llama_seq_id i = 0; i < (llama_seq_id) N_SEQ_MAX; ++i) {
        if (s.pos[i][0] != -1 || s.pos[i][1] != -1) {
            return false;
        }
    }
    return true;
}

// a sequence is "filled" when it holds state up to the last decoded position;
// the smallest present position is implementation-dependent (recurrent memories keep only the tail state)
static bool snap_is_filled(const mem_snapshot & s) {
    for (llama_seq_id i = 0; i < (llama_seq_id) N_SEQ_MAX; ++i) {
        if (s.pos[i][0] < 0 || s.pos[i][1] != N_FILL - 1) {
            return false;
        }
    }
    return true;
}

static std::string snap_str(const mem_snapshot & s) {
    std::string res = "{";
    for (llama_seq_id i = 0; i < (llama_seq_id) N_SEQ_MAX; ++i) {
        res += string_format(" [%d] = %d..%d", i, s.pos[i][0], s.pos[i][1]);
    }
    return res + " }";
}

static llama_context_ptr make_ctx(const common_params & params, llama_model * model, bool unified) {
    auto cparams = common_context_params_to_llama(params);
    cparams.n_seq_max = N_SEQ_MAX;
    cparams.n_ctx     = std::max<uint32_t>(cparams.n_ctx, 256);
    cparams.n_batch   = std::max<uint32_t>(cparams.n_batch,  32);
    cparams.n_ubatch  = std::max<uint32_t>(cparams.n_ubatch, 32);
    cparams.kv_unified = unified;
    return llama_context_ptr{llama_init_from_model(model, cparams)};
}

// a full-range wildcard rm must clear every sequence and must not fail;
// the memory must stay decodable afterwards - stale tails crash the next decode
static test_status test_wildcard_rm(const common_params & params, llama_model * model, bool unified) {
    auto ctx = make_ctx(params, model, unified);
    if (!ctx || !fill_seqs(ctx.get())) {
        return test_status::FAIL;
    }

    const bool ok = llama_memory_seq_rm(llama_get_memory(ctx.get()), -1, -1, -1);
    const mem_snapshot s = snapshot(ctx.get());
    if (!ok || !snap_is_empty(s)) {
        LOG_ERR("%s: wildcard rm(-1) failed (ret=%d): %s\n", __func__, ok, snap_str(s).c_str());
        return test_status::FAIL;
    }

    if (!decode_after(ctx.get())) {
        LOG_ERR("%s: decode failed after the wildcard rm\n", __func__);
        return test_status::FAIL;
    }

    return test_status::PASS;
}

// any negative seq_id must behave exactly like -1 (full-range and partial-range rm)
static test_status test_wildcard_eq(const common_params & params, llama_model * model, bool unified) {
    for (llama_seq_id wild : { (llama_seq_id) -2, (llama_seq_id) -7 }) {
        for (llama_pos p0 : { (llama_pos) -1, (llama_pos) 2 }) {
            auto ctx_a = make_ctx(params, model, unified);
            auto ctx_b = make_ctx(params, model, unified);
            if (!ctx_a || !ctx_b || !fill_seqs(ctx_a.get()) || !fill_seqs(ctx_b.get())) {
                return test_status::FAIL;
            }

            const bool ret_a = llama_memory_seq_rm(llama_get_memory(ctx_a.get()), -1,   p0, -1);
            const bool ret_b = llama_memory_seq_rm(llama_get_memory(ctx_b.get()), wild, p0, -1);

            if (ret_a != ret_b || !(snapshot(ctx_a.get()) == snapshot(ctx_b.get()))) {
                LOG_ERR("%s: seq_id %d behaves differently from seq_id -1 (p0=%d)\n", __func__, wild, p0);
                return test_status::FAIL;
            }

            // both memories must stay decodable after the removal
            if (!decode_after(ctx_a.get()) || !decode_after(ctx_b.get())) {
                LOG_ERR("%s: decode failed after seq_rm (seq_id %d, p0=%d)\n", __func__, wild, p0);
                return test_status::FAIL;
            }
        }
    }

    return test_status::PASS;
}

// the whole-context state APIs must treat any negative seq_id like -1
static test_status test_state_eq(const common_params & params, llama_model * model, bool unified) {
    auto ctx = make_ctx(params, model, unified);
    if (!ctx || !fill_seqs(ctx.get())) {
        return test_status::FAIL;
    }

    const size_t size_a = llama_state_seq_get_size(ctx.get(), -1);
    const size_t size_b = llama_state_seq_get_size(ctx.get(), -2);

    if (size_a == 0 || size_a != size_b) {
        LOG_ERR("%s: state size mismatch: -1 -> %zu, -2 -> %zu\n", __func__, size_a, size_b);
        return test_status::FAIL;
    }

    std::vector<uint8_t> buf_a(size_a), buf_b(size_b);
    const size_t n_a = llama_state_seq_get_data(ctx.get(), buf_a.data(), buf_a.size(), -1);
    const size_t n_b = llama_state_seq_get_data(ctx.get(), buf_b.data(), buf_b.size(), -2);

    if (n_a != size_a || n_b != size_b) {
        LOG_ERR("%s: state blob size mismatch after read (n_a=%zu n_b=%zu)\n", __func__, n_a, n_b);
        return test_status::FAIL;
    }

    // the restore path must accept the same wildcard: clear, then restore via -2
    llama_memory_clear(llama_get_memory(ctx.get()), true);
    const size_t n_set = llama_state_seq_set_data(ctx.get(), buf_a.data(), buf_a.size(), -2);

    // the blob header records the seq_id it was requested with (io_magic + seq_id), so the two
    // blobs legitimately differ in that field - compare the rest
    memset(buf_a.data() + 4, 0, sizeof(llama_seq_id));
    memset(buf_b.data() + 4, 0, sizeof(llama_seq_id));

    if (buf_a != buf_b) {
        LOG_ERR("%s: state blobs differ between seq_id -1 and -2 (n_a=%zu n_b=%zu)\n", __func__, n_a, n_b);
        return test_status::FAIL;
    }

    const mem_snapshot s = snapshot(ctx.get());
    if (n_set != size_a || !snap_is_filled(s)) {
        LOG_ERR("%s: state restore via -2 failed (n_set=%zu size=%zu): %s\n", __func__, n_set, size_a, snap_str(s).c_str());
        return test_status::FAIL;
    }

    return test_status::PASS;
}

// seq_cp/seq_keep/seq_add/seq_div/seq_pos_min/seq_pos_max need a concrete sequence:
// invalid seq_ids must be rejected without changing the memory
static test_status test_concrete_safe(const common_params & params, llama_model * model, bool unified) {
    auto ctx = make_ctx(params, model, unified);
    if (!ctx || !fill_seqs(ctx.get())) {
        return test_status::FAIL;
    }

    llama_memory_t mem = llama_get_memory(ctx.get());
    const mem_snapshot before = snapshot(ctx.get());

    // with --kv-unified BIG is a valid id (the mapping reaches LLAMA_MAX_SEQ) - test_big_id covers it
    const std::vector<llama_seq_id> invalid = unified ?
        std::vector<llama_seq_id>{ NEG, TOO_BIG } :
        std::vector<llama_seq_id>{ NEG, TOO_BIG, BIG };

    for (const llama_seq_id id : invalid) {
        llama_memory_seq_keep(mem, id);
        llama_memory_seq_add(mem, id, -1, -1, 2);
        llama_memory_seq_div(mem, id, -1, -1, 2);
        llama_memory_seq_cp(mem, id, 0, -1, -1);
        llama_memory_seq_cp(mem, 0, id, -1, -1);
    }

    if (!(snapshot(ctx.get()) == before)) {
        LOG_ERR("%s: memory changed by an invalid seq_id call: %s -> %s\n", __func__,
                snap_str(before).c_str(), snap_str(snapshot(ctx.get())).c_str());
        return test_status::FAIL;
    }

    if (llama_memory_seq_pos_min(mem, NEG) != -1 || llama_memory_seq_pos_max(mem, NEG) != -1) {
        LOG_ERR("%s: seq_pos_min/max must report -1 for an invalid seq_id\n", __func__);
        return test_status::FAIL;
    }

    return test_status::PASS;
}

// with --kv-unified the KV mapping reaches LLAMA_MAX_SEQ, so BIG is a valid id: seq_keep(big)
// must drop the rest in every cache of the memory. A memory cleared in one cache only (e.g.
// attention cleared, recurrent kept) is the regression this check was added for
static test_status test_big_id(const common_params & params, llama_model * model) {
    auto ctx = make_ctx(params, model, true);
    if (!ctx || !fill_seqs(ctx.get())) {
        return test_status::FAIL;
    }

    llama_memory_t mem = llama_get_memory(ctx.get());
    const mem_snapshot before = snapshot(ctx.get());

    llama_memory_seq_keep(mem, BIG);

    const mem_snapshot after   = snapshot(ctx.get());
    const bool         cleared = snap_is_empty(after);

    // DSV4 keeps per-sequence streams even when unified, so it refuses the id as a whole -
    // every other memory accepts it and clears all its caches
    char arch[64] = { 0 };
    llama_model_meta_val_str(model, "general.architecture", arch, sizeof(arch));
    const bool dsv4 = strcmp(arch, "deepseek4") == 0;

    if (!cleared && !(dsv4 && after == before)) {
        LOG_ERR("%s: seq_keep(%d) with kv_unified left the memory inconsistent: %s -> %s\n", __func__,
                BIG, snap_str(before).c_str(), snap_str(after).c_str());
        return test_status::FAIL;
    }

    // the memory must stay decodable after the keep
    if (!decode_after(ctx.get())) {
        LOG_ERR("%s: decode failed after seq_keep(%d) with kv_unified\n", __func__, BIG);
        return test_status::FAIL;
    }

    return test_status::PASS;
}

// concrete seq_ids must keep working exactly as before
static test_status test_regression(const common_params & params, llama_model * model, bool unified) {
    // seq_rm(0) removes exactly sequence 0, leaving sequence 1 untouched
    {
        auto ctx = make_ctx(params, model, unified);
        if (!ctx || !fill_seqs(ctx.get())) {
            return test_status::FAIL;
        }
        llama_memory_t mem = llama_get_memory(ctx.get());

        const mem_snapshot before = snapshot(ctx.get());

        if (!llama_memory_seq_rm(mem, 0, -1, -1)) {
            LOG_ERR("%s: seq_rm(0) failed\n", __func__);
            return test_status::FAIL;
        }

        const mem_snapshot after = snapshot(ctx.get());
        const bool seq0_gone = after.pos[0][0] == -1 && after.pos[0][1] == -1;
        const bool seq1_same = after.pos[1][0] == before.pos[1][0] && after.pos[1][1] == before.pos[1][1];
        if (!seq0_gone || !seq1_same) {
            LOG_ERR("%s: seq_rm(0) did not remove exactly sequence 0: %s -> %s\n", __func__,
                    snap_str(before).c_str(), snap_str(after).c_str());
            return test_status::FAIL;
        }
    }

    // seq_keep(1) keeps exactly sequence 1
    {
        auto ctx = make_ctx(params, model, unified);
        if (!ctx || !fill_seqs(ctx.get())) {
            return test_status::FAIL;
        }
        llama_memory_t mem = llama_get_memory(ctx.get());

        const mem_snapshot before = snapshot(ctx.get());

        llama_memory_seq_keep(mem, 1);

        const mem_snapshot after = snapshot(ctx.get());
        const bool seq0_gone = after.pos[0][0] == -1 && after.pos[0][1] == -1;
        const bool seq1_same = after.pos[1][0] == before.pos[1][0] && after.pos[1][1] == before.pos[1][1];
        if (!seq0_gone || !seq1_same) {
            LOG_ERR("%s: seq_keep(1) did not keep exactly sequence 1: %s -> %s\n", __func__,
                    snap_str(before).c_str(), snap_str(after).c_str());
            return test_status::FAIL;
        }
    }

    return test_status::PASS;
}

constexpr size_t N_CHECKS = 6;

struct test_results {
    test_status wildcard_rm = test_status::SKIP;
    test_status wildcard_eq = test_status::SKIP;
    test_status state_eq    = test_status::SKIP;
    test_status concrete    = test_status::SKIP;
    test_status regression  = test_status::SKIP;
    test_status big_id      = test_status::SKIP;

    test_status operator[](size_t i) const {
        switch (i) {
            case 0: return wildcard_rm;
            case 1: return wildcard_eq;
            case 2: return state_eq;
            case 3: return concrete;
            case 4: return regression;
            case 5: return big_id;
        }
        return test_status::SKIP;
    }
};

static test_results run_tests(const common_params & params, llama_model * model, bool unified) {
    test_results res;

    // the checks need decoded positions in the memory; models that do not track per-sequence
    // positions (e.g. diffusion LLMs) cannot exercise the seq_id semantics
    {
        auto ctx = make_ctx(params, model, unified);
        if (!ctx || !fill_seqs(ctx.get())) {
            test_results fail;
            fail.wildcard_rm = fail.wildcard_eq = fail.state_eq = fail.concrete = fail.regression = test_status::FAIL;
            fail.big_id = unified ? test_status::FAIL : test_status::SKIP;
            return fail;
        }
        if (!snap_is_filled(snapshot(ctx.get()))) {
            LOG_INF("%s: skipping model - decoding does not populate per-sequence positions\n", __func__);
            return res;
        }
    }

    res.wildcard_rm = test_wildcard_rm(params, model, unified);
    res.wildcard_eq = test_wildcard_eq(params, model, unified);
    res.state_eq    = test_state_eq(params, model, unified);
    res.concrete    = test_concrete_safe(params, model, unified);
    res.regression  = test_regression(params, model, unified);
    res.big_id      = unified ? test_big_id(params, model) : test_status::SKIP;

    return res;
}

static test_results run_tests_for_model(const std::string & model_path, const struct common_params & base_params, bool unified) {
    struct common_params params = base_params;
    params.model.path = model_path;

    auto llama_init = common_init_from_params(params, true);
    auto * model = llama_init->model();

    if (model == nullptr) {
        LOG_ERR("%s: failed to init model '%s'\n", __func__, model_path.c_str());
        // a model that cannot be loaded is a failure, not a skip
        test_results fail;
        fail.wildcard_rm = fail.wildcard_eq = fail.state_eq = fail.concrete = fail.regression = test_status::FAIL;
        fail.big_id = unified ? test_status::FAIL : test_status::SKIP;
        return fail;
    }

    return run_tests(params, model, unified);
}

static void print_usage(int, char ** argv) {
    LOG("\n");
    LOG("%s - checks negative seq_id handling in the memory APIs\n", argv[0]);
    LOG("\n");
    LOG("  %s -m your_model.gguf\n", argv[0]);
    LOG("\n");
    LOG("  %s --models tests/test-models\n", argv[0]);
    LOG("\n");
}

int main(int argc, char ** argv) {
    std::setlocale(LC_NUMERIC, "C");

    common_params params;
    params.sampling.seed = 1234;
    params.n_predict = 1;

    common_init();

    // extract our own --models DIR option before handing the rest to the common arg parser
    std::string models_dir;
    std::vector<char *> filtered_argv;
    filtered_argv.push_back(argv[0]);
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--models") == 0) {
            if (i + 1 >= argc) {
                LOG_ERR("%s: --models requires a directory argument\n", __func__);
                return 1;
            }
            models_dir = argv[i + 1];
            i++;
        } else {
            filtered_argv.push_back(argv[i]);
        }
    }
    filtered_argv.push_back(nullptr);
    const int fargc = (int)filtered_argv.size() - 1;

    // in --models mode there is no single model; set a placeholder so the common parser's
    // "--model is required" check passes (each model is set individually inside the loop)
    if (!models_dir.empty()) {
        params.model.path = models_dir;
    }

    if (!common_params_parse(fargc, filtered_argv.data(), params, LLAMA_EXAMPLE_COMMON, print_usage)) {
        return 1;
    }

    llama_backend_init();

    std::vector<std::string> models;
    if (!models_dir.empty()) {
        if (!std::filesystem::exists(models_dir) || !std::filesystem::is_directory(models_dir)) {
            LOG_ERR("%s: models directory '%s' does not exist\n", __func__, models_dir.c_str());
            return 1;
        }

        for (const auto & entry : std::filesystem::directory_iterator(models_dir)) {
            if (entry.is_regular_file() && entry.path().extension() == ".gguf") {
                models.push_back(entry.path().string());
            }
        }
        std::sort(models.begin(), models.end());

        if (models.empty()) {
            LOG_ERR("%s: no .gguf models found in '%s'\n", __func__, models_dir.c_str());
            return 1;
        }
    } else {
        models.push_back(params.model.path);
    }

    size_t name_width = 5; // "Model"
    for (const auto & model_path : models) {
        name_width = std::max(name_width, std::filesystem::path(model_path).filename().string().size());
    }

    LOG("%-*s  %-10s  %-11s  %-11s  %-8s  %-8s  %-10s  %-8s\n",
        (int) name_width, "Model", "kv_unified", "wildcard rm", "wildcard eq", "state eq", "concrete", "regression", "big id");
    common_log_flush(common_log_main());

    size_t n_pass[N_CHECKS] = { 0 };
    size_t n_fail[N_CHECKS] = { 0 };

    // every model runs twice: once as-is, once with the unified KV cache
    for (const bool unified : { false, true }) {
        for (const auto & model_path : models) {
            const auto name = std::filesystem::path(model_path).filename().string();

            LOG("%-*s  %-10s", (int) name_width, name.c_str(), unified ? "true" : "false");

            const test_results res = run_tests_for_model(model_path, params, unified);

            for (size_t t = 0; t < N_CHECKS; ++t) {
                LOG("  %s", test_status_str(res[t]));
                switch (res[t]) {
                    case test_status::PASS: n_pass[t]++; break;
                    case test_status::FAIL: n_fail[t]++; break;
                    case test_status::SKIP: break;
                }
            }
            LOG("\n");
            common_log_flush(common_log_main());
        }
    }

    common_log_flush(common_log_main());

    size_t total_fail = 0;
    size_t total_pass = 0;
    for (size_t t = 0; t < N_CHECKS; ++t) {
        total_fail += n_fail[t];
        total_pass += n_pass[t];
    }

    LOG_INF("%s: %zu models x 2 modes, %zu checks, %zu passed, %zu failed\n",
            __func__, models.size(), N_CHECKS, total_pass, total_fail);

    return total_fail == 0 ? 0 : 1;
}
